### ISSUE TITLE
Dockerize travisci tests

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor-plugins#13]
In an effort to make running tests on travis more predictable, we should move to a Docker strategy rather than using the travis ubuntu image. This will make it much easier for open source contributors and development in general.

**Comment by bagipriyank** [comment]
it would be great if we can have this. i've had a hard time to make sure everything builds successfully. what worked locally for me didn't work with travis ubuntu image, and vice versa. i've been committing, rebasing and issuing a pr to test my changes since travis-python docker container available from docker hub is 3 years old and running a super old version of ubuntu. long story short it has been painful. :(
